name: csvImport CI/CD

on:
 push:
    branches: [ main ]
 
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build project with Maven
      run: mvn -B package --file pom.xml
    - name: Setup GCP Service account
      uses: google-github-actions/auth@v0
      with:
        project_id: ingka-cowr-ishare-test
        service_account: ${{ secrets.GCP_SA }}
        export_default_credentials: false
    - name: Deploy cloud functions
      id: deploy
      uses: google-github-actions/deploy-cloud-functions@v0
      with:
          name: testDeploy
          runtime: java11
          project_id: ingka-cowr-ishare-test
          entry_point: functions.testDeploy

    - name: make the url aunthenticated
      run: |
          gcloud functions add-iam-policy-binding testDeploy --member="allUsers" --role="roles/cloudfunctions.invoker"
    - name: test the url
      run: curl "${{ steps.deploy.outputs.url }}"
